# Generated by Django 3.0.1 on 2019-12-23 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0006_partida_clubes'),
        ('rodadas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodada',
            name='nome',
        ),
        migrations.AddField(
            model_name='rodada',
            name='Partida',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='partidas.Partida'),
        ),
    ]
