# Generated by Django 3.0.1 on 2019-12-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temporadas', '0002_remove_temporada_melhor_jogador'),
        ('rodadas', '0004_auto_20191223_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodada',
            name='Partida',
        ),
        migrations.AddField(
            model_name='rodada',
            name='Temporada',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='temporadas.Temporada'),
        ),
    ]
