# Generated by Django 3.0.1 on 2019-12-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodadas', '0005_auto_20191223_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rodada',
            old_name='Temporada',
            new_name='temporada',
        ),
        migrations.AlterField(
            model_name='rodada',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
