# Generated by Django 3.0.1 on 2019-12-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodadas', '0009_rodada_numero_rodada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='numero_rodada',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
