# Generated by Django 3.0.1 on 2019-12-23 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0006_auto_20191222_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubePartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clube', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clubes.Clube')),
            ],
        ),
    ]
