# Generated by Django 2.2.1 on 2019-05-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0001_initial'),
        ('gols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gol',
            name='jogador',
            field=models.ManyToManyField(max_length=2, to='clubes.Clube'),
        ),
    ]
