# Generated by Django 3.0.1 on 2019-12-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0003_auto_20191222_2033'),
        ('jogadores', '0012_auto_20191222_2151'),
        ('gols', '0003_remove_gol_jogador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gol',
            old_name='nome',
            new_name='data',
        ),
        migrations.AddField(
            model_name='gol',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gol',
            name='jogador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='jogadores.Jogador'),
        ),
        migrations.AddField(
            model_name='gol',
            name='partida',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='partidas.Partida'),
        ),
    ]
