# Generated by Django 3.0.1 on 2019-12-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gols', '0004_auto_20191223_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='gol',
            name='gol_contra',
            field=models.BooleanField(default=False),
        ),
    ]
