# Generated by Django 3.0.1 on 2019-12-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gols', '0005_gol_gol_contra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gol',
            name='data',
            field=models.DateTimeField(null=True),
        ),
    ]
