# Generated by Django 3.0.1 on 2019-12-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gols', '0006_auto_20191223_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gol',
            name='partida',
        ),
    ]
