# Generated by Django 3.0.1 on 2019-12-23 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogadores', '0012_auto_20191222_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.TextField(default='')),
                ('melhor_jogador', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='jogadores.Jogador')),
            ],
        ),
    ]
