# Generated by Django 3.0.1 on 2019-12-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temporadas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='melhor_jogador',
        ),
    ]
