# Generated by Django 3.0.1 on 2019-12-23 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadios', '0003_auto_20191222_2119'),
        ('clubes', '0002_remove_clube_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clube',
            name='data_fundacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clube',
            name='estadio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estadios.Estadio'),
        ),
        migrations.AddField(
            model_name='clube',
            name='nome',
            field=models.TextField(default='erro'),
        ),
    ]
