# Generated by Django 3.0.1 on 2019-12-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_auto_20191222_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='estadio',
        ),
    ]
