# Generated by Django 3.0.1 on 2019-12-23 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadios', '0003_auto_20191222_2119'),
        ('clubes', '0004_remove_clube_estadio'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='estadio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estadios.Estadio'),
        ),
    ]
