# Generated by Django 3.0.1 on 2019-12-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0006_auto_20191222_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clubes'),
        ),
    ]
