# Generated by Django 3.0.1 on 2019-12-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0018_remove_jogador_clubeatual'),
        ('clubes', '0007_clube_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='jogadores',
            field=models.ManyToManyField(to='jogadores.Jogador'),
        ),
    ]
