# Generated by Django 2.2.1 on 2019-05-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('clubeAtual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubes.Clube')),
            ],
        ),
    ]
