# Generated by Django 3.0.1 on 2019-12-23 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_auto_20191222_2119'),
        ('jogadores', '0003_auto_20191222_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='clubeAtual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clubes.Clube'),
        ),
    ]
