# Generated by Django 3.0.1 on 2019-12-23 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0004_jogador_clubeatual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='clubeAtual',
        ),
    ]
