# Generated by Django 3.0.1 on 2019-12-23 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0005_clube_estadio'),
        ('jogadores', '0005_remove_jogador_clubeatual'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='clubeAtual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clubes.Clube'),
        ),
    ]
