# Generated by Django 3.0.1 on 2019-12-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0006_jogador_clubeatual'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='apelido',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jogador',
            name='data_nascimento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nome',
            field=models.TextField(default=''),
        ),
    ]
