# Generated by Django 3.0.1 on 2019-12-23 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0009_remove_jogador_apelido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='data_nascimento',
        ),
    ]
