# Generated by Django 3.0.1 on 2019-12-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0010_remove_jogador_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='apelido',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jogador',
            name='data_nascimento',
            field=models.DateTimeField(null=True),
        ),
    ]
