# Generated by Django 3.0.1 on 2019-12-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0011_auto_20191222_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
