# Generated by Django 3.0.1 on 2019-12-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0012_auto_20191222_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='idade',
            field=models.IntegerField(default=18, null=True),
        ),
    ]
