# Generated by Django 3.0.1 on 2019-12-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0013_jogador_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='idade',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
