# Generated by Django 3.0.1 on 2019-12-24 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0006_auto_20191222_2135'),
        ('jogadores', '0014_auto_20191223_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='clubeAtual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clubes.Clube'),
        ),
    ]
