# Generated by Django 3.0.1 on 2019-12-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0015_auto_20191223_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='apelido',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='data_nascimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
