# Generated by Django 3.0.1 on 2019-12-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0016_auto_20191223_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jogadores'),
        ),
    ]
