# Generated by Django 3.0.1 on 2019-12-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0017_jogador_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='clubeAtual',
        ),
    ]
