# Generated by Django 2.2.1 on 2019-05-09 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodadas', '0001_initial'),
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='rodada',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='rodadas.Rodada'),
        ),
    ]
