# Generated by Django 3.0.1 on 2019-12-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodadas', '0001_initial'),
        ('jogadores', '0012_auto_20191222_2151'),
        ('estadios', '0003_auto_20191222_2119'),
        ('partidas', '0003_auto_20191222_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='nome',
        ),
        migrations.AddField(
            model_name='partida',
            name='data_fim',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='data_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='estadio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='estadios.Estadio'),
        ),
        migrations.AddField(
            model_name='partida',
            name='melhor_jogador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='jogadores.Jogador'),
        ),
        migrations.AddField(
            model_name='partida',
            name='quantidade_torcida',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='rodada',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='rodadas.Rodada'),
        ),
    ]
