# Generated by Django 3.0.1 on 2019-12-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0004_auto_20191223_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='quantidade_torcida',
            new_name='publico',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='rodada',
        ),
    ]
