# Generated by Django 3.0.1 on 2019-12-23 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temporadas', '0001_initial'),
        ('partidas', '0006_partida_clubes'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='temporada',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='temporadas.Temporada'),
        ),
    ]
