# Generated by Django 3.0.1 on 2019-12-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0008_partida_rodada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='melhor_jogador',
        ),
    ]
