# Generated by Django 3.0.1 on 2019-12-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0009_remove_partida_melhor_jogador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='clubes',
        ),
    ]
