# Generated by Django 3.0.1 on 2019-12-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0006_auto_20191222_2135'),
        ('partidas', '0010_remove_partida_clubes'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='clubes',
            field=models.ManyToManyField(max_length=2, to='clubes.Clube'),
        ),
    ]
