# Generated by Django 3.0.1 on 2019-12-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0006_auto_20191222_2135'),
        ('partidas', '0012_auto_20191223_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='clube_mandante',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='clube_visitante',
        ),
        migrations.AddField(
            model_name='partida',
            name='clubes',
            field=models.ManyToManyField(max_length=2, to='clubes.Clube'),
        ),
    ]
