# Generated by Django 3.0.1 on 2019-12-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes_partidas', '0001_initial'),
        ('partidas', '0014_auto_20191223_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='clube_mandante',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='clube_visitante',
        ),
        migrations.AddField(
            model_name='partida',
            name='clubes',
            field=models.ManyToManyField(max_length=2, to='clubes_partidas.ClubePartida'),
        ),
    ]
