# Generated by Django 3.0.1 on 2019-12-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0015_auto_20191223_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
