# Generated by Django 3.0.1 on 2019-12-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gols', '0007_remove_gol_partida'),
        ('clubes', '0008_clube_jogadores'),
        ('jogadores', '0018_remove_jogador_clubeatual'),
        ('partidas', '0016_auto_20191223_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='gols',
            field=models.ManyToManyField(max_length=2, to='gols.Gol'),
        ),
        migrations.AddField(
            model_name='partida',
            name='melhor_jogador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='jogadores.Jogador'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='clubes',
            field=models.ManyToManyField(max_length=2, to='clubes.Clube'),
        ),
    ]
