# Generated by Django 3.0.1 on 2019-12-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0018_remove_jogador_clubeatual'),
        ('partidas', '0017_auto_20191224_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='melhor_jogador',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='jogadores.Jogador'),
        ),
    ]
