# Generated by Django 3.0.1 on 2019-12-23 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0006_auto_20191222_2135'),
        ('partidas', '0003_auto_20191222_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clubes.Clube')),
                ('partidas', models.ManyToManyField(to='partidas.Partida')),
            ],
        ),
    ]
