# Generated by Django 3.0.1 on 2019-12-22 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estadios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadio',
            name='nome',
        ),
        migrations.AddField(
            model_name='estadio',
            name='data_fundacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
