# Generated by Django 3.0.1 on 2019-12-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadios', '0002_auto_20191222_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadio',
            name='nome',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='data_fundacao',
            field=models.DateTimeField(null=True),
        ),
    ]
